version: '2.3'
services:
  rcssserver3d:
    build: 
      context: ./rcssserver3d/
    image: rcssserver3d
    environment: 
      SERVER_PORT: "${SERVER_PORT}"
      AGENT_PORT: "${AGENT_PORT}"
    command: ["--agent-port","${AGENT_PORT}","--server-port","${SERVER_PORT}"]
  roboviz:
    build: 
      context: ./roboviz/mesa
      args: 
        ROBOVIZ_RELEASE: 1.7.0
    image: roboviz:mesa
    volumes:
      - "/tmp/.X11-unix:/tmp/.X11-unix:rw"
      - "/home/${USER}/.Xauthority:/root/.Xauthority"
    environment:
      XAUTHORITY: /root/.Xauthority
      DISPLAY: ${DISPLAY}
    command: ["--serverHost=rcssserver3d","--serverPort=${SERVER_PORT}"]
    depends_on:
      - rcssserver3d
