version: '2.3'

services:
  rcssserver3d:
    image: parthjindal/rcssserver3d:latest
    environment: 
      SERVER_PORT: "${SERVER_PORT}"
      AGENT_PORT: "${AGENT_PORT}"
    ports: 
    - "${AGENT_PORT}:${AGENT_PORT}"
    command: ["--agent-port","${AGENT_PORT}","--server-port","${SERVER_PORT}"]
    
  roboviz:
    image: parthjindal/roboviz:nvidia-1.7
    runtime: nvidia
    volumes:
      - "/tmp/.X11-unix:/tmp/.X11-unix:rw"
      - "/tmp/.docker.xauth:/tmp/.docker.xauth:rw"
    environment:
      XAUTHORITY: /tmp/.docker.xauth
      DISPLAY: ${DISPLAY}
    command: ["--serverHost=rcssserver3d","--serverPort=${SERVER_PORT}"]
    depends_on:
      - rcssserver3d
